# A.Importation des librairies

In [4]:
import numpy as np

## 1.Tableau

### 1.1.Tableau à 1D

In [5]:
tab_1D=np.array ([2,4,6,8,10,12,14])

In [6]:
tab_1D

array([ 2,  4,  6,  8, 10, 12, 14])

In [7]:
print(tab_1D)

[ 2  4  6  8 10 12 14]


In [8]:
print(tab_1D.shape)

(7,)


In [10]:
type(tab_1D)

numpy.ndarray

### 1.2.Tableau à 2D

In [11]:
tab_2D=np.array([[1,3,5,7,8], 
                 [10,30,50,70,80]])

In [12]:
tab_2D

array([[ 1,  3,  5,  7,  8],
       [10, 30, 50, 70, 80]])

In [13]:
print('Dimension du tableau', tab_2D.shape)

Dimension du tableau (2, 5)


In [14]:
print('Type du tableau', type(tab_2D))

Type du tableau <class 'numpy.ndarray'>


In [15]:
print(tab_2D)

[[ 1  3  5  7  8]
 [10 30 50 70 80]]


### 1.3.Tableau à 3D

In [16]:
tab_3D=np.array([[[1,3,5,7,8,6], 
                 [15,35,55,75,85,65]]])

In [17]:
print('Dimension du tableau', tab_3D.shape)

Dimension du tableau (1, 2, 6)


In [18]:
print('Le type du tableau', type(tab_3D))

Le type du tableau <class 'numpy.ndarray'>


### 1.4.Tableau à 4D

In [19]:
tab_4D=np.array([[[[11,22,33,44,55],
                  [111,221,331,441,551],
                  [112,222,332,442,552]]]])

In [20]:
print (tab_4D)

[[[[ 11  22  33  44  55]
   [111 221 331 441 551]
   [112 222 332 442 552]]]]


In [21]:
print('Dimension du tableau', tab_4D.shape)

Dimension du tableau (1, 1, 3, 5)


In [22]:
print (type(tab_4D))

<class 'numpy.ndarray'>
